version: "3.7"

services:
  app:
    build: .
    ports:
      - "8082:8082"
    networks:
      - s-network

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    networks:
      - s-network

volumes:
  data-volume:

networks:
  s-network:
    driver: bridge